### PR TITLE
Add release dates to the CHANGELOG

### LINKED ISSUE #348: Add release dates to the changelog
### Feature description

Add release dates to the [CHANGELOG](https://github.com/fabiospampinato/cash/blob/master/CHANGELOG.md).

### Feature motivation

It's good that there's a changelog which is kept up to date, but it's not very useful without dates.

From [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how): **How do I make a good changelog?**

>  The release date of each version is displayed.

### PR DESCRIPTION
**Pull request by chocolateboy**
Closes #348

\+ cleanup, including:

  - merge [duplicate sections](https://github.com/fabiospampinato/bump/issues/17)\*
  - snip non-semantic changes
  - consistent formatting
  - fix some typos

Also made it clear that, since v3.0.0, Cash is written in TypeScript and bundles its own TypeScript typings (rendering @types/cash [obsolete](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44533)), since this wasn't obvious previously.

\* duplicates:

| occurrences | version |
|-------------|---------|
| 4           | 1.2.2   |
| 4           | 1.2.0   |
| 3           | 1.3.0   |
| 2           | 2.3.9   |
| 2           | 2.3.8   |
| 2           | 1.3.4   |

### CODE REVIEW

**Comment by fabiospampinato** [comment]
> * duplicates:

I'm not sure what that table means.

Could we do the following?:

- Use regular quotation marks and apostrophes rather then typographic ones.
- Wrap the release date in parenthesis rather than separating it with a hyphen.
- Link to the respective github release tag whenever possible.
- Prefix versions with "v" at least.

**Comment by chocolateboy** [comment]
> I'm not sure what that table means.

Versions/sections appear the specified number of times in the changelog, e.g. for v1.2.2:

- https://github.com/fabiospampinato/cash/blob/8.0.0/CHANGELOG.md#version-122
- https://github.com/fabiospampinato/cash/blob/8.0.0/CHANGELOG.md#version-122-1
- https://github.com/fabiospampinato/cash/blob/8.0.0/CHANGELOG.md#version-122-2
- https://github.com/fabiospampinato/cash/blob/8.0.0/CHANGELOG.md#version-122-3

> Use regular quotation marks and apostrophes rather then typographic ones.

The old changelog uses both. I can't see any "smart" quotes in this version?

> Wrap the release date in parenthesis rather than separating it with a hyphen.

> Link to the respective github release tag whenever possible.

> Prefix versions with "v" at least.

Done.

> Update bump's configuration file too.

As the author of bump, I figured you'd be the best person to do that :-)

**Comment by fabiospampinato** [comment]
> Versions/sections appear the specified number of times in the changelog, e.g. for v1.2.2:

Oh that's right, yeah, it looks like there's some cleanup to do there as well.

> The old changelog uses both. I can't see any "smart" quotes in this version?

I think I just misread the diff 🤦‍♀️

> Done.

Thanks.

> As the author of bump, I figured you'd be the best person to do that :-)

I can take care of that if you want, that would have to wait a few days probably though, I'm currently working on another thing that I need to release first.

**Comment by fabiospampinato** [comment]
I've merged these changes in and updated bump's configuration, thanks 👍

**Pull request closed without merging**
