### PR TITLE
Bump karma, karma-chrome-launcher, karma-qunit, karma-sauce-launcher

### PR DESCRIPTION
**Pull request by limonte**
Potential fix for https://github.com/fabiospampinato/cash/issues/336#issuecomment-614115052

### CODE REVIEW

**Comment by fabiospampinato** [comment]
👍

**Comment by limonte** [comment]
Looks good:

image

the branch build is failing because it doesn't have access to env secrets. The branch build shouldn't be triggered for `master` branch.

**Comment by limonte** [comment]
You can go ahead with the release, I'll check out how to exclude `master` from branch builds.

**Comment by limonte** [comment]
I DID NOT EVEN NOTICED THAT YOU MANAGED TO MOVE CASH TO YOUR ACCOUNT!!!!

CONGRATS :tada: :tada: :tada:

**Comment by limonte** [comment]
Now, the thing with 

image

is that you have parallel configuration on travis-ci.com in addition to travis-ci.org

One of them is free for OSS, another one is paid. I don't remember which exactly is paid. In GitHub apps you need to disable the paid one either completely or for this repo.

**Comment by limonte** [comment]
.com is the paid one: https://travis-ci.com/plans

**Comment by fabiospampinato** [comment]
> You can go ahead with the release

Done 👍

> I DID NOT EVEN NOTICED THAT YOU MANAGED TO MOVE CASH TO YOUR ACCOUNT!!!!
> CONGRATS 🎉 🎉 🎉

😄 thanks! 

> In GitHub apps you need to disable the paid one either completely or for this repo.

I think I did it but it's still broken 🤔 I don't know, as long as one of them works it's not a big deal.

**Pull request merged**
