### PR TITLE
Extend utility methods

### PR DESCRIPTION
**Pull request by DataTables**
This PR adds:

* Support for `$.isPlainObject` (https://github.com/fabiospampinato/cash/pull/334)
* Support for `$.extend(deep, ...)` (https://github.com/fabiospampinato/cash/issues/196)
* Support for `$.each()` with objects (https://github.com/fabiospampinato/cash/issues/104)/

I've added tests for them and I've tried to keep the existing coding style.

The one thing I haven't been sure about is the TypeScript part for `$.each` with objects - while the code runs, the typing wouldn't expect an object to be passed in, just still an ArrayLike...

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Awesome, thanks. Right now I'm busy with other things for merging this, but overall it looks ok, there are some minor style differences and typescript issues but I can take care of those, in the meantime I'd just say:

- Can you remove the files under dist/* from this PR? They just make a lot of noise, I'll update them with the next release.
- The minified and gzip-ed size of the library is important for us, I'd be great if you could spend some time optimizing for that, if you can't I can do it when merging this. 
  - As a example of this the following line of code:
    ```js
    return x !== null && typeof x === 'object' && x !== window && Object.getPrototypeOf(x) == Object.prototype;
    ```
	could probably be written in a more compact, and gzip-friendly, way:
    ```js
    return !!x && x.prototype === Object.prototype;
    ```

**Comment by DataTables** [comment]
> `x.prototype === Object.prototype`

doesn't work I'm afraid - e.g.

```
> var a = {};
> a.prototype
< undefined
```

I'll see if I can figure out a way to remove the dist files from the current PR - I wasn't sure about including them.

**Comment by fabiospampinato** [comment]
Sorry about the delay in getting back to this, right now my priority is releasing v1.9 final of the [app](https://github.com/notable/notable) I'm working on, that's possible at least more than 10 days away, but I'll get back to this once the first beta is published, which should take roughly 7 days or less (assuming no particular setbacks).

**Comment by DataTables** [comment]
No worries. And Notable looks awesome - about to play with it :-)

**Comment by fabiospampinato** [comment]
> No worries. And Notable looks awesome - about to play with it :-)

In that case I'd go straight to the v1.9 alphas (they are quite stable at this point, and although it may not look like it pretty much everything changed, v1.9 is like a different app that sort of looks like the old one): https://github.com/notable/notable-experimental/releases

**Comment by fabiospampinato** [comment]
I'm going to split this commit into 3 ones, so that I can review everything in a more compartmentalized way.

**Comment by fabiospampinato** [comment]
I just merged the changes related to `$.isPlainObject`, changes I made:

- The documentation was missing
- Objects created like this: `Object.create ( null )` weren't being recognized properly.
- The types were a little wonky.
- I moved its implementation into the `type_checking.ts` file

**Comment by fabiospampinato** [comment]
I just merged the changes related to `$.each`:

- I updated slightly the readme
- Some types required tweaking, however not all issues could be resolved since apparently a "plain object" type in TypeScript can't be written

**Comment by fabiospampinato** [comment]
Merged the stuff for `$.extend` too:

- `let` can't be used in tests as some browsers that run those tests don't support that
- I've essentially just performed some minor changes to make the implementation shorter

**Comment by DataTables** [comment]
Awesome - many thanks for pulling these in and updating them for the Cash requirements. I'm looking forward to experimenting with DataTables a bit more. Will report back as I progress with it :-).

**Comment by fabiospampinato** [comment]
👍 Everything should be available in v8.1 now. I'm sorry about how long this took to get merged!

**Pull request merged**
